// src/app/components/layout/app-layout/app-layout.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterOutlet } from '@angular/router';
import { AppHeaderComponent } from '../app-header/app-header.component';

@Component({
  selector: 'app-app-layout',
  standalone: true,
  imports: [CommonModule, RouterOutlet, AppHeaderComponent],
  templateUrl: './app-layout.component.html',
  styleUrl: './app-layout.component.scss'
})
export class AppLayoutComponent {
  currentYear = new Date().getFullYear();
}

<div class="min-h-screen flex flex-col bg-gray-50 dark:bg-gray-900">
    <!-- Header will be added here -->
    <app-app-header></app-app-header>

    <main class="flex-grow container mx-auto p-4">
        <router-outlet></router-outlet>
    </main>

    <footer class="bg-white dark:bg-gray-800 border-t border-gray-200 dark:border-gray-700">
        <div class="container mx-auto p-4 text-center text-sm text-gray-600 dark:text-gray-400">
            &copy; {{currentYear}} AI Fight Club - Human Edge Competitive Analysis
        </div>
    </footer>
</div>

// src/components/layout/app-layout.tsx
'use client';

import React from 'react';
import { useLog } from '@/lib/logging/log-provider';
import { AppHeader } from '@/components/layout/app-header';

interface AppLayoutProps {
  children: React.ReactNode;
}

/**
 * AppLayout component
 * 
 * Main layout component for the application
 * Follows React best practices with proper component structure
 */
export function AppLayout({ children }: AppLayoutProps) {
  const { addLog } = useLog();
  
  // Log when the layout mounts
  React.useEffect(() => {
    addLog('debug', 'AppLayout mounted', {
      timestamp: new Date(),
      environment: process.env.NODE_ENV
    });
    
    return () => {
      addLog('debug', 'AppLayout unmounted', {
        timestamp: new Date()
      });
    };
  }, [addLog]);
  
  return (
    <div className="min-h-screen flex flex-col">
      <AppHeader />
      
      <main className="flex-grow container mx-auto p-4">
        {children}
      </main>
      
      <footer className="bg-gray-100 p-4 border-t">
        <div className="container mx-auto text-center text-sm text-gray-600">
          &copy; {new Date().getFullYear()} AI Fight Club - Human Edge Competitive Analysis
        </div>
      </footer>
    </div>
  );
}
